# Puerto estándar para que se conecten los Arduinos/ESP32 por WiFi o Ethernet
listener 1883
allow_anonymous true

# Puerto WebSockets para que tu interfaz de React lea la telemetría en el navegador
listener 9001
protocol websockets
allow_anonymous true
